- hosts: servicesnode
  vars_files:
    - ondemand-config.yml
  vars:
    terraform_workspace: default
  tasks:
  - name: Destroy Kubernetes cluster   
    shell: >-
      kubectl delete cluster {{ terraform_workspace }}
    when:
      - "k8s_ood_enable|default(false)|bool == true"
    register: destroy
