# workflow to redploy ML102 on the training environment
#
# 1. Get the list of all training/trainer home directories
# 2. Remove any "ml102_workshop" directories in the homes
# 3. Remove the ML102 apptainer image
# 4. Pull the apptainer image
#
# Following this, any user that starts a new ML102 session
# will get the version from the newly downloaded image
#
# Note: this doesn't redeploy the OOD ML102 app
---
- name: Redeploy ML102
  become: yes
  hosts: webnode
  pre_tasks:
    - name: List home directories
      find:
        paths: /home/shared
        file_type: directory
        recurse: no
      register: homes_find

    - debug:
        var: item.path
      with_items: "{{ homes_find.files }}"

    - name: Remove any ML102 directories in homes
      ansible.builtin.file:
        path: "{{ item.path }}/ml102_workshop"
        state: absent
        recurse: yes
      with_items: "{{ homes_find.files }}"

    - name: Remove the ML102 apptainer image
      ansible.builtin.file:
        path: /opt/ml102_workshop/ML102.sif
        state: absent

  roles:
    - ml102_workshop
