---
roles:
  - name: osc.open_ondemand
    version: "v3.0.3"

collections:
  - name: community.general
    version: 8.1.0
    type: galaxy
  - name: amazon.aws
    version: 7.0.0
    type: galaxy
  - name: community.crypto.x509_certificate
    version: 2.16.1
    type: galaxy