---
- name: Workload | Prerequisites
  include_tasks: prerequisites.yml

- name: Workload | Create and initialize clusterctl and cloud manager
  block:
    - name: Workload | Read clouds.yaml
      slurp:
        src: "{{ clouds_yaml_location }}"
      register: file_content

    - name: Workload | Decode the base64 encoded version of the YAML file and assign it to a variable
      set_fact:
        file_contents: "{{ file_content['content'] | b64decode | from_yaml }}"

    - name: Workload | Create and initialize clusterctl
      include_tasks: configure-install-clusterctl.yml

    - name: Workload | Create and initialize cloud manager
      include_tasks: install-cloud-manager.yml
  when:
    - clouds_yaml_file.stat.exists


