---
- name: Workload | Setting kubernetes OOD enabled boolean to {{ k8s_ood_enable }}
  set_fact:
    enable_k8s_openondemand: "{{ k8s_ood_enable }}"

- name: Workload | Prerequisites
  include_tasks: prerequisites.yml
  when:
    - "enable_k8s_openondemand|default(false)|bool == true"


- name: Workload | Create and initialize clusterctl and cloud manager
  block:
    - name: Workload | Read clouds.yaml
      slurp:
        src: "{{ clouds_yaml_location }}"
      register: file_content

    - name: Workload | Decode the base64 encoded version of the YAML file and assign it to a variable
      set_fact:
        file_contents: "{{ file_content['content'] | b64decode | from_yaml }}"

    - name: Workload | Check cluster {{ cluster_name }} is initialized
      shell: >-
        kubectl get cluster {{ cluster_name }}
      register: cluster_intialized
      ignore_errors: true

    - name: Workload | Create and initialize clusterctl
      include_tasks: configure-install-clusterctl.yml
      when: cluster_intialized.stdout == ''

    - name: Workload | Create and initialize cloud manager
      include_tasks: install-cloud-manager.yml
      when: cluster_intialized.stdout == ''

  when:
    - "enable_k8s_openondemand|default(false)|bool == true"
    - clouds_yaml_file.stat.exists


