---
- name: Ensure pip is installed
  ansible.builtin.dnf:
    name:
      - python3-devel
      - python3-pip
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure pip is installed
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure paramiko pip module is present
  ansible.builtin.pip:
    name: paramiko
