---
- name: Ensure pip is installed
  ansible.builtin.dnf:
    name:
      - python3-devel
      - python3-pip
    state: present
  when: ansible_os_family == "RedHat"
  become: true

- name: Ensure pip is installed
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present
  when: ansible_os_family == "Debian"
  become: true

- name: Ensure paramiko pip module is present
  ansible.builtin.pip:
    name: paramiko

- name: Creating {{ tmp_dir }} if it does not exist
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755

- name: Check that the {{ cluster_namespace }} {{ cluster_name }}-kubeconfig exists
  stat:
    path: "{{ tmp_dir }}/{{ cluster_name }}.kubeconfig"
  register: new_cluster_config

- name: Get {{ cluster_name }} cluster kubeconfig yaml 
  shell: >-
    kubectl get secret -n {{ cluster_namespace }} {{ cluster_name }}-kubeconfig 
    -o jsonpath='{.data.value}'|base64 -d > {{ tmp_dir }}/{{ cluster_name }}.kubeconfig
  when: not new_cluster_config.stat.exists

- name: Copy {{ cluster_name }} cluster kubeconfig yaml to persistent location
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ cluster_name }}.kubeconfig"
    dest: "~/.kube/{{ cluster_name }}.kubeconfig"
    mode: '0640'
    remote_src: yes
