---
- name: Defaults | Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    line: '{{ hostvars[item]["ansible_default_ipv4"]["address"] }} {{ hostvars[item]["ansible_hostname"] }} {{ hostvars[item]["ansible_nodename"] }}'
    state: present
  with_items: "{{ groups['servers'] }}"

- name: Defaults | setup hosts ood-idp
  lineinfile:
    dest: /etc/hosts
    line: '{{ hostvars["servicesnode"]["ansible_default_ipv4"]["address"] }} ood-idp.flexi.nesi'
    state: present

- name: Defaults | setup hosts ood
  lineinfile:
    dest: /etc/hosts
    line: '{{ hostvars["webnode"]["ansible_default_ipv4"]["address"] }} ood.flexi.nesi'
    state: present