---  
- name: Defaults | Full system upgrade
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist

- name: Defaults | Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Defaults | Reboot after upgrade
  reboot:
  when: reboot_required_file.stat.exists == true