---
- name: Pre-Check Openstack | Check for environment variables
  include_tasks: precheck.yml

- name: Pre-Check Openstack | Creating {{ tmp_dir }} if it does not exist
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755

- name: Pre-Check Openstack | Copy clouds.yaml to {{ tmp_dir }}
  copy:
    src: "{{ clouds_yaml_local_location }}"
    dest: "{{ clouds_yaml_location }}"
    mode: 0640