---
- name: Kubernetes | Get kube-api machine name
  shell: >-
    kubectl get machine | grep {{ cluster_name }}-control-plane | awk '{ print $1 }'
  register: kube_api_machine

- name: Kubernetes | Get kube-api ip
  shell: >-
    kubectl describe machine {{ kube_api_machine.stdout }} | grep Address: | awk '{ print $2 }'
  register: kube_api_ip

- debug:
    var: kube_api_machine.stdout

- debug:
    var: kube_api_ip.stdout

- name: Kubernetes | Add kube-api host to "temp_control_plane" group
  add_host:
    groups: temp_control_plane
    name: "{{ kube_api_ip.stdout }}"

# - name: Add a host alias that we reach through a tunnel (Ansible 2.0 and newer)
#   ansible.builtin.add_host:
#     hostname: '{{ new_ip }}'
#     ansible_host: '{{ inventory_hostname }}'
#     ansible_port: '{{ new_port }}'