---
- name: Kubernetes | Setting OOD enabled boolean to {{ ood_enabled }}
  set_fact:
    enable_openondemand: "{{ ood_enabled }}"

- name: Kubernetes | Bootstrapping kubernetes cluster for OOD
  block:
    - name: Kubernetes | Create ondemand-bootstrap.yml
      copy:
        src: "files/ondemand-bootstrap.yml"
        dest: "/tmp/ondemand-bootstrap.yml"
        mode: 0644

    - name: Kubernetes | Generate clouds.yaml secret
      shell: >-
        kubectl --kubeconfig /tmp/{{ cluster_name }}.kubeconfig apply \
        -f /tmp/ondemand-bootstrap.yml
      become: true
  when:
    - "enable_openondemand|default(false)|bool == true"
  become: true