---
- name: Kubernetes | Setting OOD enabled boolean to {{ ood_enabled }}
  set_fact:
    enable_openondemand: "{{ ood_enabled }}"

- name: Kubernetes | Bootstrapping kubernetes cluster for OOD
  block:
    - name: Kubernetes | Create ondemand-bootstrap.yml
      copy:
        src: "files/ondemand-bootstrap.yml"
        dest: "{{ tmp_dir }}/ondemand-bootstrap.yml"
        mode: 0644

    - name: Kubernetes | Generate clouds.yaml secret
      shell: >-
        kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply \
        -f {{ tmp_dir }}/ondemand-bootstrap.yml

    - name: Kubernetes | Create ondemand-secrets.yml
      copy:
        src: "files/ondemand-secret.yml"
        dest: "{{ tmp_dir }}/ondemand-secret.yml"
        mode: 0644

    - name: Kubernetes | Generate ondemand serviceaccount secret
      shell: >-
        kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply \
        -f {{ tmp_dir }}/ondemand-secret.yml
    
    # - name: Kubernetes | Setting OIDC auth boolean to {{ kube_oidc_auth }}
    #   set_fact:
    #     enable_oidc_auth: "{{ kube_oidc_auth }}"

    # - name: Kubernetes | Update kube-api hosts temp var
    #   include_tasks: add-kube-api-hosts-temp.yml
    #   when:
    #     - "enable_oidc_auth|default(false)|bool == true"

  when:
    - "enable_openondemand|default(false)|bool == true"