---
- name: Web Node | Setting OOD enabled boolean to {{ k8s_ood_enable }}
  set_fact:
    enable_openondemand: "{{ k8s_ood_enable }}"

- name: Web Node | Bootstrapping OnDemand Web node
  block:
    - name: Web Node | Bootstrapping ondemand k8s
      include_tasks: bootstrap-ondemand-k8s.yml
  when:
    - "enable_openondemand|default(false)|bool == true"
  become: true