---
- name: Creates directory
  file:
    path: /etc/docker
    state: directory
    
- name: Copy daemon.json to nodes
  copy:
    src: ../template/daemon.json
    dest: /etc/docker/daemon.json

- name: Docker Installation
  apt:
    name: docker.io
    state: present
    update_cache: true