---
- name: Kubernetes OIDC | Get contents kube-api yaml
  slurp:
    src: "{{ kube_config_dir }}/manifests/file.yml"
  register: kube_api_pod_yaml

- name: Kubernetes OIDC | Extract kube-api yaml
  set_fact:
    kube_api_pod_yaml_data: "{{ kube_api_pod_yaml.stdout | b64decode | from_yaml }}"

- name: Kubernetes OIDC | Update kube-api yaml with OIDC hostalias
  set_fact:
    kube_api_pod_yaml_data_updated: "{{ kube_api_pod_yaml_data | combine(newdata, recursive=True) }}"
  vars: 
    newdata:
      spec:
        hostAliases:
            - ip: "{{ kube_oidc_ip }}"
              hostnames:
              - "{{ kube_oidc_hostname }}"

- name: Kubernetes OIDC | Write kube-api yaml file
  copy:
    content: '{{ kube_api_pod_yaml_data_updated | to_nice_yaml }}'
    dest: "{{ tmp_dir }}/{{ cluster_name }}-kube-api.yml"

- name: Kubernetes OIDC | Update kube-api yaml
  shell: >-
    kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply -f {{ tmp_dir }}/{{ cluster_name }}-kube-api.yml