cluster_name: "kubernetes"

## Change this to use another Kubernetes version, e.g. a current beta release
apt_kube_version: 1.23.0-00
kube_version: v1.23.4

kube_apiserver_bind_address: 0.0.0.0
kube_apiserver_port: 6443  # (https)

# Kubernetes internal network for services, unused block of space.
kube_service_addresses: 10.233.0.0/18

# internal network. When used, it will assign IP
# addresses from this range to individual pods.
# This network must be unused in your network infrastructure!
kube_pods_subnet: 10.233.64.0/18

# A port range to reserve for services with NodePort visibility.
# Inclusive at both ends of the range.
kube_apiserver_node_port_range: "30000-32767"

is_kube_master: "{{ inventory_hostname in groups['kube_control_plane'] }}"
kube_apiserver_count: "{{ groups['kube_control_plane'] | length }}"
kube_apiserver_address: "{{ ansible_host | default(fallback_ips[inventory_hostname]) }}"
first_kube_control_plane_address: "{{ hostvars[groups['kube_control_plane'][0]]['ansible_host'] }}"
kube_apiserver_endpoint: https://{{ first_kube_control_plane_address }}:{{ kube_apiserver_port }}

# Kubernetes settings
kube_api_anonymous_auth: true

# Editing those values will almost surely break something.
kube_config_dir: /etc/kubernetes
kube_manifest_dir: "{{ kube_config_dir }}/manifests"

# This is where all the cert scripts and certs will be located
kube_cert_dir: "{{ kube_config_dir }}/ssl"

## Variables for OpenID Connect Configuration https://kubernetes.io/docs/admin/authentication/
## To use OpenID you have to deploy additional an OpenID Provider (e.g Dex, Keycloak, ...)

kube_oidc_auth: false
kube_oidc_url: https://ood-idp.training.data.nesi.org.nz/realms/ondemand
kube_oidc_client_id: kubernetes
## Optional settings for OIDC
kube_oidc_username_claim: preferred_username
kube_oidc_username_prefix: "-"
kube_oidc_groups_claim: groups
kube_oidc_groups_prefix: 'oidc:'
# Copy oidc CA file to the following path if needed
kube_oidc_ca_file: "{{ kube_cert_dir }}/zero_ca.crt"
# Optionally include a base64-encoded oidc CA cert
kube_oidc_ca_cert: LS0tLS1CRU.....