# K8s cluster name
cluster_name: "training-k8s"

# Change this to use another Kubernetes version, e.g. a current beta release
apt_kube_version: 1.23.0-00
kube_version: v1.23.4

kube_apiserver_bind_address: 0.0.0.0
kube_apiserver_port: 6443  # (https)

# Kubernetes internal network for services, unused block of space.
kube_service_addresses: 10.233.0.0/18

# internal network. When used, it will assign IP
# addresses from this range to individual pods.
# This network must be unused in your network infrastructure!
kube_pods_subnet: 10.233.64.0/18

# A port range to reserve for services with NodePort visibility.
# Inclusive at both ends of the range.
kube_apiserver_node_port_range: "30000-32767"

# Kubernetes settings
kube_api_anonymous_auth: true

## Variables for OpenID Connect Configuration https://kubernetes.io/docs/admin/authentication/
## To use OpenID you have to deploy additional an OpenID Provider (e.g Dex, Keycloak, ...)

kube_oidc_auth: true
kube_oidc_url: https://ood-idp.training.data.nesi.org.nz/realms/ondemand
kube_oidc_client_id: kubernetes
## Optional settings for OIDC
kube_oidc_username_claim: preferred_username
kube_oidc_username_prefix: "-"
kube_oidc_groups_claim: groups
kube_oidc_groups_prefix: 'oidc:'
# Copy oidc CA file to the following path if needed
kube_oidc_ca_file: "{{ kube_cert_dir }}/zero_ca.crt"
# Optionally include a base64-encoded oidc CA cert
kube_oidc_ca_cert: <I_WILL_PASS_YOU_THIS-MAYBE_SET_AS_AN_ENV>