---
- name: Pre-Checks | Setting facts for KUBE_CONFIG_BASE64 and CLOUDS_YAML_BASE64
  set_fact:
    kube_config_bas64: "{{ lookup('ansible.builtin.env', 'KUBE_CONFIG_BASE64') | default('') }}"
    clouds_yaml_base64: "{{ lookup('ansible.builtin.env', 'CLOUDS_YAML_BASE64') | default('') }}"

- name: Pre-Checks | Check KUBE_CONFIG_BASE64 and CLOUDS_YAML_BASE64 variables are defined
  assert:
    that:
      - kube_config_bas64 is defined and kube_config_bas64 != ''
      - clouds_yaml_base64 is defined and clouds_yaml_base64 != ''