---
- name: Pre-Checks | Setting facts for KUBE_CONFIG_BASE64
  set_fact:
    kube_config_bas64: "{{ lookup('ansible.builtin.env', 'KUBE_CONFIG_BASE64') | default('') }}"

- name: Pre-Checks | Ensure clouds.yaml file exists
  stat:
    path: "{{ clouds_yaml_local_location }}"
  register: clouds_yaml_local_file

- debug:
    var: clouds_yaml_local_file

- name: Pre-Checks | Check KUBE_CONFIG_BASE64 variables are defined
  assert:
    that:
      - kube_config_bas64 is defined and kube_config_bas64 != ''
      - clouds_yaml_local_file.stat.exists