name: Deploy

on:
  push:
    branches:
      - main
# TODO: also for pull requests into main
# TODO: add dev branch too?

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
      OS_APPLICATION_CREDENTIAL_NAME: ${{ secrets.OS_APPLICATION_CREDENTIAL_NAME }}
      OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      TF_VAR_key_pair: ${{ secrets.KEY_PAIR_NAME }}
      TF_VAR_extra_public_keys: '${{ vars.EXTRA_PUBLIC_KEYS }}'
    steps:
      - uses: actions/checkout@v3
      - run: python --version
      - run: |
          import os
          with open(os.environ['TF_VAR_key_file'], 'w') as fh:
            fh.write(os.environ['PRIVATE_KEY_CONTENT'])
        shell: python
        env:
          TF_VAR_key_file: "${{ runner.temp }}/my_ci_private_key"
          PRIVATE_KEY_CONTENT: ${{ secrets.PRIVATE_KEY_CONTENT }}
      - run: chmod 400 ${TF_VAR_key_file}
        env:
          TF_VAR_key_file: "${{ runner.temp }}/my_ci_private_key"
      - name: Terraform initialise
        run: terraform init -input=false
        env:
          TF_VAR_key_file: "${{ runner.temp }}/my_ci_private_key"
      - run: echo "GITHUB_REF = $GITHUB_REF"
      - run: echo "GITHUB_REF_NAME = $GITHUB_REF_NAME"
      - run: echo "GITHUB_HEAD_REF = $GITHUB_HEAD_REF"
      - run: echo "GITHUB_BASE_REF = $GITHUB_BASE_REF"
      - run: echo "GITHUB_EVENT_NAME = $GITHUB_EVENT_NAME"
      - name: Write ansible secrets file
        run: |
          cp secrets.yml.example secrets.yml
          sed -i'' "s/CHANGEME_KEYCLOAK_ADMIN_PASSWORD/$KEYCLOAK_ADMIN_PASSWORD/" secrets.yml
          sed -i'' "s/CHANGEME_LDAP_ADMIN_PASSWORD/$LDAP_ADMIN_PASSWORD/" secrets.yml
        working-directory: ansible/vars
        env:
          KEYCLOAK_ADMIN_PASSWORD: '${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}'
          LDAP_ADMIN_PASSWORD: '${{ secrets.LDAP_ADMIN_PASSWORD }}'
      - name: Write ansible ondemand config file
        run: |
          cp ondemand-config.yml.example ondemand-config.yml
          sed -i'' "s/CHANGEME_OIDC_CRYPTO_PASSPHRASE/$OIDC_CRYPTO_PASSPHRASE/" ondemand-config.yml
        working-directory: ansible/vars
        env:
          OIDC_CRYPTO_PASSPHRASE: '${{ secrets.OIDC_CRYPTO_PASSPHRASE }}'
      - name: Install ansible dependencies
        run: ansible-galaxy install -r requirements.yml
        working-directory: ansible
      - name: Switch terraform workspace
        run: terraform workspace select -or-create=true ${GITHUB_BASE_REF:-$GITHUB_REF_NAME}
        env:
          TF_VAR_key_file: "${{ runner.temp }}/my_ci_private_key"
      - name: Terraform plan
        run: terraform plan -input=false
        env:
          TF_VAR_key_file: "${{ runner.temp }}/my_ci_private_key"
      - name: Terraform destroy first (?)
        run: terraform apply -destroy -input=false -auto-approve
        env:
          TF_VAR_key_file: "${{ runner.temp }}/my_ci_private_key"
      - name: Terraform plan
        run: terraform plan -input=false
        env:
          TF_VAR_key_file: "${{ runner.temp }}/my_ci_private_key"
      - name: Terraform apply
        run: terraform apply -input=false -auto-approve
        env:
          TF_VAR_key_file: "${{ runner.temp }}/my_ci_private_key"
